# Generated by Django 6.0.1 on 2026-01-16 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('decision', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('reasons', models.JSONField()),
                ('rules_triggered', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
